version: '3.3'

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  metrics-back:
  metrics-front:

services:
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - '9090'
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - metrics-back

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - metrics-back
      - metrics-front
    restart: always
